name: create_report
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'notebook.ipynb'
jobs:
  create-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
      - name: Generate report
        run: jupyter nbconvert --to markdown $GITHUB_WORKSPACE/notebook.ipynb --no-input --output $GITHUB_WORKSPACE/reports/pair_regression.md

      - name: Commit and push generated report if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Report Generator"
          git add $GITHUB_WORKSPACE/reports/*
          git diff --staged --quiet || git commit -m "Generated new pair_regression report in reports/pair_regression.md"
          git push
  
